#!/usr/bin/env python
# Copyright 2014-2026 The PySCF Developers. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Yu Hsuan Liang
#         Gengzhi Yang
#         Hong-Zhou Ye
#         Timothy C. Berkelbach
#

import numpy as np
from functools import reduce
from pyscf.scf.addons import canonical_orth_
from pyscf import lib


def select_natorb(n, v, thresh=None, pct_occ=None, nact=None):
    nvir = v.shape[1]
    n = abs(n)
    order = np.argsort(n)[::-1]
    n, v = n[order], v[:, order]
    pct_occ_sum = np.cumsum(n/np.sum(n))
    if nact is None:
        if pct_occ is None:
            if thresh is None:
                raise RuntimeError('No FNO thresholding variables are provided.')
            nact = np.count_nonzero(n > thresh)
        else:
            nact = np.count_nonzero(pct_occ_sum < pct_occ)
    nact = min(nact, nvir)
    vact = v[:, :nact]
    return vact


def pseudocano(vir_energy, vact):
    fvv = lib.dot(vact.T.conj()*vir_energy, vact)
    eact, v = np.linalg.eigh(fvv)
    vact = lib.dot(vact, v)
    return eact, vact


def safe_eigh(f, s, lindep_thr=1e-6):
    x = canonical_orth_(s, lindep_thr)
    forth = reduce(lib.dot, (x.T.conj(), f, x))
    e, u = np.linalg.eigh(forth)
    return e, lib.dot(x, u)


def summarize_domain(a, log, prefix, count_zero=False):
    a = np.array(a, copy=True)
    if not count_zero:
        a = a[a > 0]
    log.info('%s: Min %d | Max %d | Ave %d', prefix, a.min(), a.max(),
             a.mean().round().astype(int))


def autofrag_atom(mol, H2heavy=False):
    ''' Group non-ghost atoms into fragments. Return fragment definitions by
        atom indices

    Args:
        mol (gto.Mole or pbc.gto.Cell):
            PySCF Mole object.
        H2heavy (bool):
            Wether to include H atoms into the fragment of the nearest heavy
            atom (e.g., a CH3 group). Default is False, which means every atom
            defines an individual fragment.
            In case of no heavy atoms (e.g., a H chain), this variable is ignored
            and every H atom defines a fragment.

    Return:
        frag_atmlist (nested list):
            Fragment definition by atom indices. E.g., [[0],[1,5],[2,3,4],...] means
                fragment 1 consists of atom 0
                fragment 2 consists of atom 1 and 5
                fragment 3 consists of atom 2, 3, and 4
                ...
    '''
    if H2heavy:
        get_dist = lambda x, y: ((x[:, None, :]-y)**2.).sum(axis=-1)

        if hasattr(mol, 'lattice_vectors'):  # mol is actually a Cell object
            alat = mol.lattice_vectors()
        else:
            alat = None
        cs = mol.atom_charges()
        rs = mol.atom_coords()
        idx_H = np.where(cs == 1)[0]
        idx_X = np.where(cs > 1)[0]
        if idx_X.size > 0:
            if alat is None:
                d2 = get_dist(rs[idx_H], rs[idx_X])
                H2Xmap = np.argmin(d2, axis=1)
            else:
                d2 = []
                for jx in [-1, 0, 1]:
                    for jy in [-1, 0, 1]:
                        for jz in [-1, 0, 1]:
                            a = np.dot(np.array([jx, jy, jz]), alat)
                            d2.append(get_dist(rs[idx_H], rs[idx_X]+a))
                d2 = np.hstack(d2)
                H2Xmap = np.argmin(d2, axis=1) % len(idx_X)
            frag_atmlist = [None] * len(idx_X)
            for i, iX in enumerate(idx_X):
                iHs = np.where(H2Xmap == i)[0]
                l = np.asarray(np.concatenate([[iX], idx_H[iHs]]),
                               dtype=int).tolist()
                frag_atmlist[i] = l
        else:   # all-H system
            print('warning: no heavy atom detected in the system; every '
                  'hydrogen atom is treated as a single fragment.')
            frag_atmlist = [[i] for i in idx_H]
    else:
        frag_atmlist = [[i] for i in np.where(mol.atom_charges() > 0)[0]]

    return frag_atmlist


def autofrag_iao(moliao, frag_type='atom', frag_atmlist=None):
    ''' Group IAOs into fragments. Return fragment definitions by IAO indices.

    Args:
        moliao (gto.Mole or pbc.gto.Cell):
            Mole/Cell object generated by `lo.iao.reference_mol`.
        frag_atmlist (nested list):
            Fragment definitions by atom indices. If not provided, `autofrag_atom`
            will be called to generate a `frag_atmlist` using `moliao` with
            `H2heavy` set to False.
        frag_type (str, case insensitive):
            How IAOs are grouped into fragments:
                'atom' (default):
                    All IAOs on an atom define a fragment.
                'shell':
                    Each shell of IAOs on an atom define a fragment.
                    E.g., 3 fragments per carbon atom, 1s, 2s and 2p.
                '1o' or 'orbital':
                    Each IAO defines a fragment. Note that this choice leads
                    to energy not invariant to rotations of a molecule.

    Returns:
        frag_lolist (nested list):
            Fragment definition by IAO indices. E.g., [[0],[1,5],[2,3,4],...] means
                fragment 1 consists of IAO 0
                fragment 2 consists of IAO 1 and 5
                fragment 3 consists of IAO 2, 3, and 4
                ...
    '''
    if frag_type is None:
        frag_type = 'shell'
    frag_type = frag_type.lower()
    if frag_type == '1o' or frag_type.startswith('orb'):
        frag_lolist = [[i] for i in range(moliao.nao_nr())]
    elif frag_type.startswith('at'):
        if frag_atmlist is None:
            frag_atmlist = autofrag_atom(moliao)
        frag_lolist = [np.hstack([range(p0, p1) for (b0, b1, p0, p1) in
                                  moliao.aoslice_by_atom()[atom_ids]]).tolist()
                       for atom_ids in frag_atmlist]
    elif frag_type == 'shell':
        nbas = moliao.nbas
        ao_loc = moliao.ao_loc_nr()
        frag_lolist = [list(range(*ao_loc[i:i+2])) for i in range(nbas)]
    elif frag_type == 'shell_deep':
        nbas = moliao.nbas
        ao_loc = moliao.ao_loc_nr()
        bas_nao = ao_loc[1:] - ao_loc[:-1]
        bas_ls = np.asarray([moliao.bas_angular(i) for i in range(nbas)])
        bas_nao0_sph = 2*bas_ls+1
        bas_nao0_cart = (bas_ls+1)*(bas_ls+2)//2
        if np.all(bas_nao % bas_nao0_sph == 0):
            bas_nao0 = bas_nao0_sph
        elif np.all(bas_nao % bas_nao0_cart == 0):
            bas_nao0 = bas_nao0_cart
        else:
            raise RuntimeError
        frag_lolist = [list(range(p0, p1)) for i in range(nbas) for p0, p1 in
                       lib.prange(*ao_loc[i:i+2], bas_nao0[i])]
    else:
        raise ValueError('Unknown frag_type %s' % (str(frag_type)))
    return frag_lolist


def sort_orb_by_cell(scell, lo_coeff, Ncell, s=None, kpt=np.zeros(3), pop_method='meta-lowdin',
                     Q_tol=1e-3):
    ''' Reorder LOs by unit cells in a supercel.

    Args:
        scell (pyscf.pbc.gto.Cell object):
            Supercell.
        lo_coeff (np.ndarray):
            AO coefficient matrix of LOs in supercell.
        Ncell (int):
            Number of cell in supercell.
        s (np.ndarray):
            AO overlap matrix in supercell. If not given, `s` is calculated by
                s = scell.pbc_intor('int1e_ovlp', kpts=kpt)
            where `kpt` needs to be specified (vide infra).
        kpt (np.ndarray):
            k-point for calculating the AO overlap matrix. Default is Gamma point.
        pop_method (str):
            Population method for assigning LOs to cells. Default is 'meta-lowdin'.
        Q_tol (float):
            Unused. Kept for API compatibility.

    Returns:
        lo_coeff (np.ndarray):
            Same LO coefficient matrix but reordered by cell. Let Nlo = Ncell*nlo.
            Then lo_coeff[:,i*nlo:(i+1)*nlo] gives the LOs in i-th cell.
    '''
    from pyscf.lo.orth import orth_ao
    Natm = scell.natm
    natm = Natm//Ncell
    assert(natm*Ncell == Natm)
    Nlo = lo_coeff.shape[1]
    nlo = Nlo//Ncell
    assert(nlo*Ncell == Nlo)
    Nao = lo_coeff.shape[0]
    nao = Nao // Ncell

    if s is None:
        s = scell.pbc_intor('int1e_ovlp', kpts=kpt)

    # Q values for cell assignment
    csc = reduce(np.dot, (lo_coeff.conj().T, s, orth_ao(scell, pop_method, 'ANO', s=s)))
    pop_by_atom = np.asarray([lib.einsum('ix,ix->i', csc[:, p0:p1], csc[:, p0:p1].conj())
                              for i, (b0, b1, p0, p1) in enumerate(scell.offset_nr_by_atom())])
    Q_by_cell = np.asarray([(pop_by_atom[i*natm:(i+1)*natm]**2.).sum(axis=0)**0.5
                            for i in range(Ncell)])

    def translate_orbital(coeff, tgt_cell):
        template = np.zeros_like(coeff)
        template[tgt_cell*nao:(tgt_cell+1)*nao] = coeff[:nao]
        return template

    # Cell 0 orbitals: nlo highest-Q orbitals
    Q_cell0 = Q_by_cell[0]
    cell0_orbs = np.argsort(Q_cell0)[::-1][:nlo]

    reorder = [list(cell0_orbs)]
    assigned = set(cell0_orbs)

    # Other cells: overlap-based matching
    for ic in range(1, Ncell):
        candidates = [il for il in range(Nlo) if il not in assigned]

        if len(candidates) < nlo:
            raise RuntimeError(f'sort_orb_by_cell: Not enough unassigned orbitals for cell {ic}. '
                               f'Have {len(candidates)}, need {nlo}.')

        ovlp_matrix = np.zeros((nlo, len(candidates)))
        for ii, ref_orb in enumerate(cell0_orbs):
            template = translate_orbital(lo_coeff[:, ref_orb], ic)
            for jj, cand_orb in enumerate(candidates):
                ovlp_matrix[ii, jj] = abs(np.dot(template.conj(),
                                                  np.dot(s, lo_coeff[:, cand_orb])))

        cell_ic_orbs = []
        used = set()
        for ii in range(nlo):
            best_jj = -1
            best_ovlp = -1
            for jj in range(len(candidates)):
                if jj not in used and ovlp_matrix[ii, jj] > best_ovlp:
                    best_ovlp = ovlp_matrix[ii, jj]
                    best_jj = jj
            if best_jj >= 0:
                cell_ic_orbs.append(candidates[best_jj])
                used.add(best_jj)
            else:
                raise RuntimeError(f'sort_orb_by_cell: Could not find match for orbital {ii} in cell {ic}')

        reorder.append(cell_ic_orbs)
        assigned.update(cell_ic_orbs)

    if len(assigned) != Nlo:
        import warnings
        warnings.warn(f'sort_orb_by_cell: Only assigned {len(assigned)} of {Nlo} orbitals')

    reorder = np.hstack(reorder).astype(int)
    lo_coeff = np.asarray(lo_coeff[:, reorder], order='C')

    return lo_coeff


def xyz2atom(fxyz):
    fdata = open(fxyz, 'r').read().rstrip('\n').split('\n')
    return '\n'.join(fdata[2:])


def guess_frozen(mol):
    frozen_charge_map = np.array([
        0,
        0, 0,
        1, 1, 1, 1, 1, 1, 1, 1,
        5, 5, 5, 5, 5, 5, 5, 5,
    ])
    return frozen_charge_map[mol.atom_charges()].sum()


class RaggedTensor1D:
    '''Contiguous storage for a list of tensors with different shapes.'''
    def __init__(self, shape=None, dtype=np.float64):
        if shape is not None:
            self.ntensor = len(shape)
            self.shape = shape
            self.size = np.asarray([np.prod(self.shape[i]) for i in range(self.ntensor)], dtype=int)
            self.loc = np.cumsum([0]+[self.size[i] for i in range(self.ntensor)]).astype(int)
            self.data = np.zeros(self.loc[-1], dtype=dtype)

    @property
    def dtype(self):
        return self.data.dtype

    def init_from_data(self, a):
        self.ntensor = len(a)
        self.shape = [x.shape for x in a]
        self.data = np.hstack([x.ravel() for x in a])
        self.size = np.asarray([np.prod(self.shape[i]) for i in range(self.ntensor)], dtype=int)
        self.loc = np.cumsum([0]+[self.size[i] for i in range(self.ntensor)]).astype(int)
        return self

    def __getitem__(self, index):
        return self.data[self.loc[index]:self.loc[index+1]].reshape(*self.shape[index])

    def __setitem__(self, index, val):
        self.data[self.loc[index]:self.loc[index+1]] = val.ravel()

    def copy(self):
        new = RaggedTensor1D(self.shape, self.data.dtype)
        new.data = self.data.copy()
        return new


class RaggedTensor2DTril(RaggedTensor1D):
    '''Lower-triangular 2D ragged matrix. Auto-transposes upper triangle if transpose=True.'''
    def __init__(self, n, shape, transpose, dtype=np.float64):
        self.n = n
        self.transpose = transpose
        RaggedTensor1D.__init__(self, shape, dtype)

    def __getitem__(self, index):
        i, j = index
        if i >= j:
            return RaggedTensor1D.__getitem__(self, i*(i+1)//2+j)
        elif self.transpose:
            return RaggedTensor1D.__getitem__(self, j*(j+1)//2+i).T.conj()
        else:
            return RaggedTensor1D.__getitem__(self, j*(j+1)//2+i)

    def __setitem__(self, index, val):
        i, j = index
        if i >= j:
            RaggedTensor1D.__setitem__(self, i*(i+1)//2+j, val)
        elif self.transpose:
            RaggedTensor1D.__setitem__(self, j*(j+1)//2+i, val.T.conj())
        else:
            RaggedTensor1D.__setitem__(self, j*(j+1)//2+i, val)

    def copy(self):
        new = RaggedTensor2DTril(self.n, self.shape, self.transpose, self.data.dtype)
        new.data = self.data.copy()
        return new


def _to_full(a, n):
    a = np.asarray(a)
    if a.size == n*(n+1)//2:
        a = lib.unpack_tril(a)
    elif a.size == n*n:
        pass
    else:
        raise RuntimeError
    return a


def _to_tril(a, n):
    a = np.asarray(a)
    if a.size == n*(n+1)//2:
        pass
    elif a.size == n*n:
        a = lib.pack_tril(a)
    else:
        raise RuntimeError
    return a


def zdotCNtoR(aR, aI, bR, bI, alpha=1, cR=None, beta=0):
    '''c = (a.conj()*b).real'''
    cR = lib.ddot(aR, bR, alpha, cR, beta)
    cR = lib.ddot(aI, bI, alpha, cR, 1)
    return cR


def zdotNNtoR(aR, aI, bR, bI, alpha=1, cR=None, beta=0):
    '''c = (a*b).real'''
    cR = lib.ddot(aR, bR, alpha, cR, beta)
    cR = lib.ddot(aI, bI, -alpha, cR, 1)
    return cR


def ao_index_by_atom(mol, atmlst):
    aoslices = mol.aoslice_by_atom()[:, 2:]
    ao_idx_lst = map(lambda x: np.arange(*x), aoslices[atmlst].reshape(-1, 2))
    ao_idx = reduce(np.union1d, ao_idx_lst)
    return ao_idx


def list_to_array(a):
    out = np.empty(len(a), dtype=object)
    out[:] = a
    return out
